language: node_js
node_js:
  - '5.0'
script:
  - npm install -g grunt-cli
  - grunt deploy
env:
  global:
    secure: GECSj+I7n35AEh2B+YvTVx+76ugHoOvO1mVnE2RvJBxCDwwjgyY5DmIzyvO4dpqHZTVxThk9G5g+xvzK70+g0ymGydNJIvj/8YKCJukYzmFHvWhMwkLRKtn/b1ye1M5re6Oz2n4jE7WRmUim0lC/gKP2NK5VC3MuliFTYXEowdY=
