language: node_js
node_js:
  - '0.10'
after_script:
  - node app.js
  - mv resume.html _resume.html
  - mv resume.css _resume.css
  - mv resume.pdf _resume.pdf
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git remote set-branches --add origin gh-pages
  - git fetch
  - git checkout gh-pages
  - git rm -rf .
  - mv _resume.html resume.html
  - mv _resume.css resume.css
  - mv _resume.pdf resume.pdf
  - git add resume.html
  - git add resume.css
  - git add resume.pdf
  - git commit -m "Travis build"
  - git push origin gh-pages
env:
  global:
    secure: GECSj+I7n35AEh2B+YvTVx+76ugHoOvO1mVnE2RvJBxCDwwjgyY5DmIzyvO4dpqHZTVxThk9G5g+xvzK70+g0ymGydNJIvj/8YKCJukYzmFHvWhMwkLRKtn/b1ye1M5re6Oz2n4jE7WRmUim0lC/gKP2NK5VC3MuliFTYXEowdY=
