sudo: false
language: node_js
node_js:
- '5.0'
script:
- npm install -g grunt-cli
- grunt deploy
env:
  global:
    secure: MQTns825giLGla6CjKoWFLm2E54eI9iH5Q1mCTEpJpiwG+EATrLonf8gFl+/slBiI+WMnuXgK34LxAj0h6pg2gz+zTJMqfbgIpJA4Ro95+yMP+WvVm7ZEWhysJYglj+sXgc8ETzfZlAgntbyqZsn4kXTJ6mRBh/2lwkWtrfmqng=
